/*
 * This source file was generated by the Gradle 'init' task
 */
package org.app

class App {
    val idadeMinima = 18

    val ofertas = mutableListOf<Oferta>()
    val pessoas = mutableListOf<Pessoa>()
    val telas = Telas()

    init {
        ofertas.add(Oferta(1, "Filmes"))
        ofertas.add(Oferta(2, "Séries"))
        ofertas.add(Oferta(3, "Documentários"))
        ofertas.add(Oferta(4, "Esportes"))
        ofertas.add(Oferta(5, "Futebol"))
        ofertas.add(Oferta(6, "MMA"))
        ofertas.add(Oferta(7, "Jogos"))
        ofertas.add(Oferta(8, "Música"))
        ofertas.add(Oferta(9, "Notícias"))
        ofertas.add(Oferta(10, "Cursos"))
    }

    fun rodar() {
        var continuar = true

        while (continuar) {
            val maiorDeIdade = cadastrarPessoa()

            if (maiorDeIdade) {
                continuar = perguntarSeDesejaContratarOutraPessoa()
            }
        }

        telas.mostrarRelatorioGeral(pessoas, idadeMinima)
    }

    fun cadastrarPessoa(): Boolean {
        telas.mostrarTituloCadastro()

        telas.pedirNome()
        val nome = readln()

        telas.pedirIdade()
        val idade = readln().toInt()

        val respostas = mutableListOf<RespostaOferta>()

        val pessoa = Pessoa(nome, idade, respostas)

        if (pessoa.ehMaiorDeIdade(idadeMinima)) {
            telas.mostrarOfertas(ofertas)

            telas.pedirEscolhasOfertas()
            val escolhasDigitadas = readln()

            val partes = escolhasDigitadas.split(",")
            val numerosEscolhidos = mutableListOf<Int>()

            for (parte in partes) {
                val numero = parte.toInt()

                if (numero !in numerosEscolhidos) {
                    numerosEscolhidos.add(numero)
                }
            }

            for (oferta in ofertas) {
                val aceitou = oferta.numero in numerosEscolhidos
                val resposta = RespostaOferta(oferta, aceitou)
                respostas.add(resposta)
            }

        } else {
            telas.mostrarMensagemMenorDeIdade()
        }

        pessoas.add(pessoa)

        return pessoa.ehMaiorDeIdade(idadeMinima)
    }

    fun perguntarSeDesejaContratarOutraPessoa(): Boolean {
        var opcao: Int

        do {
            telas.mostrarPerguntaContratarOutraPessoa()

            opcao = readln().toInt()

            if (opcao != 1 && opcao != 2) {
                telas.mostrarOpcaoInvalida()
            }

        } while (opcao != 1 && opcao != 2)

        return opcao == 1
    }
}

class Pessoa(
    val nome: String,
    val idade: Int,
    val respostas: MutableList<RespostaOferta>
) {
    fun ehMaiorDeIdade(idadeMinima: Int): Boolean {
        return idade >= idadeMinima
    }
}

class Oferta(
    val numero: Int,
    val nome: String
)

class RespostaOferta(
    val oferta: Oferta,
    val aceitou: Boolean
)

class Telas {
    fun mostrarTituloCadastro() {
        println()
        println("=== CADASTRO ===")
    }

    fun pedirNome() {
        print("Digite seu nome: ")
    }

    fun pedirIdade() {
        print("Digite sua idade: ")
    }

    fun mostrarMensagemMenorDeIdade() {
        println("Menor de idade, nenhuma oferta disponível")
    }

    fun mostrarOfertas(ofertas: MutableList<Oferta>) {
        println()
        println("Ofertas disponíveis para você:")

        for (oferta in ofertas) {
            println("${oferta.numero} - ${oferta.nome}")
        }
    }

    fun pedirEscolhasOfertas() {
        println()
        println("Digite os números das ofertas que deseja contratar separados por vírgula:")
        println("Exemplo: 1,5,6 (Digite sem dar espaços entre as vírgulas)")
        print("Escolhas: ")
    }

    fun mostrarPerguntaContratarOutraPessoa() {
        println()
        println("Gostaria de contratar outra assinatura para outra pessoa?")
        println("1 - Sim")
        println("2 - Não")
        print("Opção: ")
    }

    fun mostrarRelatorioGeral(pessoas: MutableList<Pessoa>, idadeMinima: Int) {
        println()
        println("=== RELATÓRIO GERAL ===")

        for (pessoa in pessoas) {
            println()
            println("Nome: ${pessoa.nome}")
            println("Idade: ${pessoa.idade}")

            if (pessoa.idade < idadeMinima) {
                println("Menor de idade: nenhuma oferta disponível")
            } else {
                println("Ofertas:")

                for (resposta in pessoa.respostas) {
                    if (resposta.aceitou) {
                        println("${resposta.oferta.numero} - ${resposta.oferta.nome} - ACEITA")
                    } else {
                        println("${resposta.oferta.numero} - ${resposta.oferta.nome} - RECUSADA")
                    }
                }
            }
        }
    }

    fun mostrarOpcaoInvalida() {
        println()
        println("Opção inválida, tente novamente!")
    }
}

fun main() {
    val app = App()
    app.rodar()
}